datasource:
  musakan:
    url: jdbc:mysql://localhost:3306/VaadinSpringBootDB
    username: musab
    password: Baba123*
    driver-class-name: com.mysql.cj.jdbc.Driver
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      hbm2ddl:
        method: update
      show_sql: true
      format_sql: true

spring:
  application:
    name: musakan-core

  hikari:
    maximum-pool-size: 10